<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-T7MUJ4G" failures="0" tests="7" name="com.practice.test.OrangeHRMTests" time="3.544" errors="2" timestamp="2023-12-29T20:48:30 EST" skipped="5">
  <testcase classname="com.practice.test.OrangeHRMTests" name="LoginLogoutTest" time="0.001">
    <skipped/>
  </testcase> <!-- LoginLogoutTest -->
  <testcase classname="com.practice.test.OrangeHRMTests" name="LoginLogoutTest" time="0.001">
    <skipped/>
  </testcase> <!-- LoginLogoutTest -->
  <testcase classname="com.practice.test.OrangeHRMTests" name="setUp" time="1.771">
    <error message="Could not initialize class com.practice.utils.JsonUtils" type="java.lang.NoClassDefFoundError">
      <![CDATA[java.lang.NoClassDefFoundError: Could not initialize class com.practice.utils.JsonUtils
at com.practice.driver.Driver.initDriver(Driver.java:27)
at com.practice.test.BaseTest.setUp(BaseTest.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:810)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:577)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:80)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:17)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException [in thread "TestNG-PoolService-1"]
at com.practice.utils.JsonUtils.<clinit>(JsonUtils.java:33)
... 19 more
]]>
    </error>
  </testcase> <!-- setUp -->
  <testcase classname="com.practice.test.OrangeHRMTests" name="setUp" time="1.771">
    <error type="java.lang.ExceptionInInitializerError">
      <![CDATA[java.lang.ExceptionInInitializerError
at com.practice.driver.Driver.initDriver(Driver.java:27)
at com.practice.test.BaseTest.setUp(BaseTest.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:810)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:577)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:80)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:17)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.RuntimeException
at com.practice.utils.JsonUtils.<clinit>(JsonUtils.java:33)
... 19 more
]]>
    </error>
  </testcase> <!-- setUp -->
  <testcase classname="com.practice.test.OrangeHRMTests" name="LoginLogoutTest" time="0.000">
    <skipped/>
  </testcase> <!-- LoginLogoutTest -->
  <testcase classname="com.practice.test.OrangeHRMTests" name="LoginLogoutTest" time="0.000">
    <skipped/>
  </testcase> <!-- LoginLogoutTest -->
  <testcase classname="com.practice.test.OrangeHRMTests" name="myTest">
    <skipped/>
  </testcase> <!-- myTest -->
</testsuite> <!-- com.practice.test.OrangeHRMTests -->
